### ISSUE TITLE
visionmedia compiler no longer working.

### ISSUE THREAD

**Issue by ProLoser** [stevelacy/gulp-haml#14]
Could it be because he renamed his org?

**Comment by stevelacy** [comment]
The two compilers are: 
```
  creationix: require('haml'),
  visionmedia: require('hamljs'),
```
`hamljs` is still published. https://www.npmjs.com/package/hamljs

Please add more information regarding the issue than "no longer working:

**Comment by ProLoser** [comment]
```
 gulp html:legacy
[18:48:15] Using gulpfile ~/Sites/main-app/gulpfile.js
[18:48:15] Starting 'html:legacy'...

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
HamlError: (Haml):12 unexpected attrs
    at hamlStream (/Users/Dean/Sites/main-app/node_modules/gulp-haml/index.js:31:6)
    at wrappedMapper (/Users/Dean/Sites/main-app/node_modules/gulp-haml/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/Users/Dean/Sites/main-app/node_modules/gulp-haml/node_modules/map-stream/index.js:96:21)
    at write (/Users/Dean/Sites/main-app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/Dean/Sites/main-app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/Dean/Sites/main-app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
    at emitReadable_ (/Users/Dean/Sites/main-app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/Dean/Sites/main-app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/Dean/Sites/main-app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)```

**Comment by stevelacy** [comment]
Check your syntax, and this issue: https://github.com/haml/haml/issues/710

**Comment by soyuka** [comment]
Because I was facing this kind of issues with both haml parsers I made a [streamable one](https://github.com/soyuka/jhaml) (gulp implementation is [here](https://github.com/soyuka/gulp-jhaml)). Mind taking a look at it?
